# Generated by Django 3.2.15 on 2023-04-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcb', '0002_auto_20230406_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'PATIENT'), ('PATIENT', 'DOCTOR')], max_length=10),
        ),
    ]
